In [5]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [78]:
def DHtransform(a, alpha, d, theta):
    m = np.matrix([
        [math.cos(theta), -math.sin(theta)*math.cos(alpha), math.sin(theta)*math.sin(alpha), a*math.cos(theta)],
        [math.sin(theta), math.cos(theta)*math.cos(alpha), -math.cos(theta)*math.sin(alpha), a*math.sin(theta)],
        [0, math.sin(alpha), math.cos(alpha), d],
        [0, 0, 0, 1]
    ])
    return m

def WAM(ltheta):
    T1 = DHtransform(0, 0, 0.333, ltheta[0])
    T2 = T1 * DHtransform(0, -math.pi/2, 0, ltheta[1]) 
    T3 = T2 * DHtransform(0, math.pi/2, 0.316, ltheta[2]) 
    T4 = T3 * DHtransform(0.0825, math.pi/2, 0, ltheta[3]) 
    T5 = T4 * DHtransform(-0.0825, -math.pi/2, 0.384, ltheta[4]) 
    T6 = T5 * DHtransform(0, math.pi/2, 0, ltheta[5]) 
    T7 = T6 * DHtransform(0.088, math.pi/2, 0, ltheta[6]) 
    return [T1,T2,T3,T4,T5,T6,T7]
    
#tmp = tmp * DHtransform(0, 0, 0.107, 0) 

In [79]:
#calculate Jacobian (forward kinematics)
ltheta=[0.1,0.2,0.3,-0.4,0.5,0.6,0.7]
Tmatrix = WAM(ltheta)
Jo = np.array((0,0,1)).reshape(-1,1)
for i in range(6):
    Jo = np.hstack((Jo, Tmatrix[i][0:3,2]))
pe = T7[0:3,3]
Jp = np.cross(Jo[:,0].T,pe.T).T
for i in range(6):
    jpi = np.cross(Jo[:,i+1].T,(pe-Tmatrix[i][0:3,3]).T).T
    Jp = np.hstack((Jp,jpi))
J = np.vstack((Jp,Jo))

In [81]:
WAM([0,0,0,0,0,0,0])[-1]

matrix([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00,  8.8000000e-02],
        [ 0.0000000e+00, -1.0000000e+00, -1.2246468e-16, -6.8000000e-02],
        [ 0.0000000e+00,  1.2246468e-16, -1.0000000e+00,  3.3300000e-01],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [76]:
Jp

array([[ 4.09330874e-02,  4.09330874e-02,  6.34180589e-02,
         3.33305268e-01, -4.95496177e-02, -3.23953636e-02,
        -6.24024999e-02],
       [-8.15119957e-02, -8.15119957e-02,  1.96175045e-02,
        -7.39919088e-03, -3.14399372e-04,  5.71309495e-02,
        -2.02741708e-02],
       [ 0.00000000e+00, -0.00000000e+00,  8.99679382e-02,
        -9.78220439e-02, -3.85346488e-02, -1.47209988e-02,
         5.86420156e-02]])

In [71]:
i=1
jpi = np.cross(Jo[:,i+1].T,(pe-Tmatrix[i][0:3,3]).T).T

In [66]:
Jo[:,1+1]

matrix([[-2.95520207e-01],
        [ 9.55336489e-01],
        [ 6.12323400e-17]])

In [57]:
np.cross(np.array((0,0,1)),pe.T).T

array([[ 0.04093309],
       [-0.081512  ],
       [ 0.        ]])

In [58]:
pe-Tmatrix[0][0:3,3]

matrix([[-0.081512  ],
        [-0.04093309],
        [ 0.06638295]])

In [59]:
Tmatrix[0][:,3]

matrix([[0.   ],
        [0.   ],
        [0.333],
        [1.   ]])